
export let FORM_ENTREVISTADOR_ENTREVISTA = {
    titulo: 'EntrevistadorEntrevista',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'EntrevistadorEntrevista',
    campos: [
    // {
    //     etiqueta: 'input',
    //     claseGrid: 'col-6',
    //     nombre: 'Id',
    //     label_i18n: 'id',
    //     placeholder_i18n: 'id',
    //     requerido: true,
    //     tipo: 'number',
    // },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'Entrevistador',
        label_i18n: 'entrevistador',
        placeholder_i18n: 'entrevistador',
        requerido: true,
        tipo: 'Entrevistador',
        key: 'Persona',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'Esntrevista',
        label_i18n: 'esntrevista',
        placeholder_i18n: 'esntrevista',
        requerido: true,
        tipo: 'Entrevista',
        // key: 'InscripcionId',
        opciones: [],
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'CodigoAbreviacion',
        label_i18n: 'codigo_abreviacion',
        placeholder_i18n: 'codigo_abreviacion',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'Activo',
        label_i18n: 'activo',
        placeholder_i18n: 'activo',
        requerido: true,
        tipo: 'checkbox',
    },
    ],
}
