
export let FORM_DESCUENTO_MATRICULA = {
    titulo: 'DescuentoMatricula',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'DescuentoMatricula',
    campos: [
    {
        etiqueta: 'select',
        claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
        nombre: 'TipoDescuentoMatricula',
        label_i18n: 'tipodescuentomatricula',
        placeholder_i18n: 'tipodescuentomatricula',
        requerido: true,
        tipo: 'TipoDescuentoMatricula',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'file',
        claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
        clase: 'form-control',
        nombre: 'Soporte',
        label_i18n: 'enlace',
        placeholder_i18n: 'enlace',
        requerido: false,
        tipo: 'pdf',
        tipoDocumento: 2,
        formatos: 'pdf',
        url: '',
        tamanoMaximo: 2,
    },
    ],
}
