
export let FORM_ENTREVISTA = {
    titulo: 'Entrevista',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Entrevista',
    campos: [
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Id',
        label_i18n: 'id',
        placeholder_i18n: 'id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Admision',
        label_i18n: 'admision',
        placeholder_i18n: 'admision',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'FechaEntrevista',
        label_i18n: 'fecha_entrevista',
        placeholder_i18n: 'fecha_entrevista',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Nota',
        label_i18n: 'nota',
        placeholder_i18n: 'nota',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'EstadoEntrevista',
        label_i18n: 'estado_entrevista',
        placeholder_i18n: 'estado_entrevista',
        requerido: true,
        tipo: 'EstadoEntrevista',
        // key: 'Name',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'TipoEntrevista',
        label_i18n: 'tipo_entrevista',
        placeholder_i18n: 'tipo_entrevista',
        requerido: true,
        tipo: 'TipoEntrevista',
        // key: 'Name',
        opciones: [],
    },
    ],
}
